<?php
class Lokaldelen_SE extends superfecta_base {
	function settings() {

		$settings['desc'] = "http://www.lokaldelen.se - This listings include data from the Swedish lokaldelen.se directory.";
		$settings['version_requirement'] = "3.0";

		return($settings);
	}
	
	function get_caller_id($thenumber,$run_param=array()) {
		
		$caller_id=null;
		
		if( (!$this->IsValidNumber('SE',$thenumber)) )
		{
			$this->DebugPrint( "Skipping Source - Not a valid Swedish number: {$thenumber}");
		}
		else
		{
			$this->DebugPrint( "Searching Lokaldelen.se ... ");
			
			$url="http://www.lokaldelen.se/navigator/-/$thenumber/1/";
			$pattern = "/<a class='fn openPreview'.*>(.*)<\/a>/U";

			if($this->SearchURL($url, $pattern, $match)) {
				$caller_id = $this->ExtractMatch($match);
			}
		}
		return($caller_id);
	}
	
}