<?php
class Google_Maps_AU extends superfecta_base {

	function settings() {
		//configuration / display parameters
		//The description cannot contain "a" tags, but can contain limited HTML. Some HTML (like the a tags) will break the UI.
		$source_desc = "http://maps.google.com.au - 	These listings include business data for Australia.<br><br>This data source requires Superfecta Module version 3.0 or higher.";
		$settings['desc'] = $source_desc;
		$settings['version_requirement'] = "3.0";
		return($settings);
	}
	
	function get_caller_id($thenumber,$run_param=array()) {

		$caller_id = null;		

		if(!$this->IsValidNumber('AU', $this->thenumber))
		{
			$this->DebugPrint("Skipping Source - Non Australian number: {$this->thenumber}");
		}
		else
		{
			$this->DebugPrint("Searching maps.google.com.au for number: {$this->thenumber}");
			
			// We'll be searching google maps
			$url = "http://maps.google.com.au/?mode=search&q={$this->thenumber}";

			// Grab the first result from google maps that matches our phone number
			$pattern="/title:\'{$this->thenumber}.*sxti:\'(.*)\'/U";
			
			if($this->SearchURL($url, $pattern, $match)){
				$caller_id = $this->ExtractMatch($match);
			}
		}

		return $this->StripHexCodes($caller_id);		
	}
}