<?php

class Google_Maps_UK extends superfecta_base {

    public $description = "http://maps.google.co.uk - These listings include business data for the UK.<br><br>This data source requires Superfecta Module version 3.0 or higher.";
    public $version_requirement = "3.0";

    function get_caller_id($thenumber, $run_param=array()) {

        $caller_id = null;

        if (!$this->IsValidNumber('UK', $this->thenumber)) {
            $this->DebugPrint("Skipping Source - Non UK number: {$this->thenumber}");
        } else {
            $this->DebugPrint("Searching maps.google.co.uk for number: {$this->thenumber}");

            // We'll be searching google maps
            $url = "http://maps.google.co.uk/?mode=search&q={$this->thenumber}";

            // Grab the first result from google maps that matches our phone number
            $pattern = "/title:\'{$this->thenumber}.*sxti:\'(.*)\'/U";

            if ($this->SearchURL($url, $pattern, $match)) {
                $caller_id = $this->ExtractMatch($t);
            }
        }

        return $caller_id;
    }

}