<?php

class LocalTel_CH extends superfecta_base {

    public static $description = "http://local.ch - 	These listings include business and residential data for Switzerland.";
    public static $version_requirement = "3.0";

    function get_caller_id($thenumber, $run_param=array()) {

        $caller_id = null;

        if ((!$this->IsValidNumber('CH', $thenumber))) {
            $this->DebugPrint("Skipping Source - Not a valid Swiss number: {$thenumber}");
        } else {
            $this->DebugPrint("Searching Local.ch-Swiss ... ");

            $url = "http://tel.search.ch/index.en.html?was=$thenumber";
            $pattern = "/class=\"(?:fn|fn org)\">(.*)<\/a>/";

            if ($this->SearchURL($url, $pattern, $match)) {
                $caller_id = $this->ExtractMatch($match);
            }
        }
        return($caller_id);
    }

}