<?php

class Who_Called extends superfecta_base {

    public $description = "http://whocalled.us - These listings are provided by other users of the whocalled service. This service requires authentication - which you configure by clicking on this datasource. <br>This data source requires Superfecta Module version 2.2.1 or higher.";
    public $version_requirement = "2.11";
    public $source_param = array(
        'Username' => array(
            'description' => 'Your user account Login on the whocalled.us web site.',
            'type' => 'text'
        ),
        'Password' => array(
            'description' => 'Your user account Password on the whocalled.us web site.',
            'type' => 'password'
        )
    );

    function get_caller_id($thenumber, $run_param=array()) {
        $debug = $this->debug;

        if ((!$this->IsValidNumber('US', $thenumber)) && (!$this->IsValidNumber('CA', $thenumber))) {
            $this->DebugPrint("Skipping Source - Not a valid US/CAN number: " . $thenumber);
        } else {
            $this->DebugPrint("Searching Who Called ... ");

            $url = "http://whocalled.us/do?action=getWho&name=" . $run_param['Username'] . "&pass=" . $run_param['Password'] . "&phoneNumber=$thenumber";
            $value = $this->get_url_contents($url);

            $variables = preg_split('/\&/i', $value);
            $dataout = array();
            foreach ($variables as $data) {
                $subvars = preg_split('/=/i', $data);
                $dataout[$subvars[0]] = $subvars[1];
            }

            $variables = $dataout;

            if ($variables['success'] == '1') {
                if (!empty($variables['who'])) {
                    $caller_id = $variables['who'];
                } else {
                    $this->DebugPrint("not found");
                }
            } else {
                $this->DebugPrint("Error Returned: " . $variables['errorMsg']);
            }
        }
        return($caller_id);
    }
}