<?php
class Any_Who extends superfecta_base {
	function settings() {

		$settings['desc'] = "http://whitepages.anywho.com - These listings include data from the AnyWho White Pages data source.";
		
		$settings['param'] = array();
		$settings['source_param'] = array();
		$settings['version_requirement'] = "3.0";

		return($settings);
	}
	
	function get_caller_id($thenumber,$run_param=array()) 
	{		
		$caller_id="";
		
		if( (!$this->IsValidNumber('US',$thenumber)) && (!$this->IsValidNumber('CA',$thenumber)) )
		{
			$this->DebugPrint( "Skipping Source - Not a valid US/CAN number: ".$thenumber);
		}
		else
		{
			$thenumber = (substr($thenumber,0,1) == 1) ? substr($thenumber,1) : $thenumber;

			$npa = substr($thenumber,0,3);
			$nxx = substr($thenumber,3,3);
			$station = substr($thenumber,6,4);

			$this->DebugPrint( "Searching Any Who with (${npa})${nxx}-${station} ... ");

			$url = "http://whitepages.anywho.com/results.php?&qnpa=$npa&qp=".$nxx.$station;
			$value = $this->get_url_contents($url);
	
			$notfound = strpos($value, "class=\"NoResultBar\"");
			$start = strpos($value, "class=\"singleName\"");
			if(!$start)
			{
				$start = strpos($value, "class=\"resultName\"");
			}
			$value = substr($value,$start+17);
			$start=strpos($value, "\">");
			$value = substr($value,$start+2);
			$end=strpos($value, "</div>");
			$value = substr($value,0,$end);
			$value = strip_tags($value);
			if($notfound)
			{
				$value="";
			}
			
			// If we found a match, return it
			if(strlen($value) > 1)
			{
				$caller_id = $value;
			}
			else
			{
				$this->DebugPrint( "not found");
			}
				
		}
		return($caller_id);
	}
	
}