<?php
class PagineBianche_IT extends superfecta_base {

	function settings() {
		//configuration / display parameters
		//The description cannot contain "a" tags, but can contain limited HTML. Some HTML (like the a tags) will break the UI.
		$source_desc = "http://www.paginebianche.it - These listings include data from the Italian PagineBianche.";

		$settings['desc'] = $source_desc;
		$settings['version_requirement'] = "3.0";

		return($settings);
	}
	
	function get_caller_id($thenumber,$run_param=array()) {

		$caller_id = null;		
		
		if(!$this->IsValidNumber('IT', $this->thenumber))
		{
			$this->DebugPrint( "Skipping Source - Non Italian number: {$this->thenumber}" );
		}
		else
		{
			$this->DebugPrint( "Searching PagineBianche - {$this->thenumber} ... " );

			$url = "http://www.paginebianche.it/execute.cgi?ver=default&font=default&btt=1&ts=106&cb=8&l=it&mr=10&rk=&om=&qs={$this->thenumber}";			
			
			if($this->SearchURL($url, '=<h3.class\=\"org\"[^>]*>(.*)</h3>=siU', $match)){
				$caller_id = $this->ExtractMatch($match);
			}
		}
			
		return($caller_id);
	}
}