<?php
class Send_to_URL extends superfecta_base {

	function settings() {
		//configuration / display parameters
		//The description cannot contain "a" tags, but can contain limited HTML. Some HTML (like the a tags) will break the UI.
		$settings['desc'] = "This source will send the number and the Caller ID to an URL for external processing.<br>The URL you enter will be sent, with the following appended to it:<br>?thenumber=<i>the CID number</i>&CLID=<i>the CID Name</i>.<br>The destination url must be able to collect and use those arguments.<br>This datasource should be one of the last data sources on your list, as it does not provide any data of its own, and can only send what information has been collected before it is run.";
		$settings['version_requirement'] = "3.0";

		$source_param = array();
		$source_param['URL_address']['desc'] = "Specify A URL to send CID/CNAM data to. Use the format 'http://url.org'";
		$source_param['URL_address']['type'] = 'text';
		$source_param['URL_address']['default'] = '';

		$settings['param'] = array();
		$settings['source_param'] = $source_param;

		return($settings);
	}

	function post_processing($cache_found,$winning_source,$first_caller_id,$run_param,$thenumber) 
	{
		if (($run_param['URL_address'] !='') && ($first_caller_id != ''))
		{
			$url=$run_param['URL_address'].'?thenumber='.$thenumber.'&CLID='.$first_caller_id;
	
			$this->DebugPrint("Send to URL: {$url}");;
	
			$value = $this->get_url_contents($url);
		}
	}
	
}
