<?php

class PhoneLookup_UK extends superfecta_base {

    public static $description = "http://www.ukphonelookup.co.uk - A datasource devoted to identifying telemarketers. These listings are provided by other users of this service.";
    public static $version_requirement = "3.0";
    public static $source_param = array(
        'SPAM_Threshold' => array(
            'description' => 'Specify the # of listings required to mark a call as spam.',
            'type' => 'number',
            'default' => 10
        )
    );

    function get_caller_id($thenumber, $run_param=array()) {

        $caller_id = null;

        if (!$this->IsValidNumber('UK', $thenumber)) {
            $this->DebugPrint("Skipping Source - Non UK number: {$thenumber}");
        } else {
            $this->DebugPrint("Searching Phone Lookup UK for number: {$thenumber}");

            $url = "http://www.ukphonelookup.co.uk/{$thenumber}-phone-number-check";
            $value = $this->get_url_contents($url);

            if (is_numeric($value)) {
                $this->DebugPrint(" value of {$value} returned ... ");

                $score = $value;
                if ($score > $run_param['SPAM_Threshold']) {
                    $this->DebugPrint(" determined to be SPAM");
                    $this->spam = true;
                } else {
                    $this->DebugPrint("Not a SPAM caller");
                }
            } else {
                $this->DebugPrint("not found");
            }
        }
        return($caller_id);
    }

}