<?php

class Paginasblancas_AR extends superfecta_base {

    public $description = "Searches Argentina http://www.paginasblancas.com.ar/ <br>CID must include area code with the leading 0.";
    public $version_requirement = "3.0";

    function get_caller_id($thenumber, $run_param=array()) {

        $caller_id = null;
        $areacode = "";
        $number2 = "";
        $number3 = "";

        if (!$this->IsValidNumber('AR', $this->thenumber, $areacode, $number2, $number3)) {
            $this->DebugPrint("Skipping Source - Non Argentina number: {$this->thenumber}");
        } else {
            $this->DebugPrint("Searching www.paginasblancas.com.ar for number: {$this->thenumber}");

            $url = "http://www.paginasblancas.com.ar/busqueda-telefono/argentina/{$areacode}-{$number2}-{$number3}";

            $pattern = "/<H2 class=\"alta\">(.*)<\/H2>/";

            if ($this->SearchURL($url, $pattern, $match)) {
                $caller_id = $this->ExtractMatch($match);
            }
        }
        return($caller_id);
    }

}