<?php

/***** ***** ***** ***** ***** ***** ***** *****
 * Module Dev notes:
 * 
 * Version history:
 *   2016-07-27 by frontrangegeeks
 * 
 ***** ***** ***** ***** ***** ***** ***** *****/

class PCRTcnam extends superfecta_base {

	public $description = "Searches Your PC Repair Tracker db - local or remote.";
	public $version_requirement = "1.7";
	public $source_param = array(

		'DB_Host' => array(
				'description' => 'Host address of the PCRT database. (Be sure to allow remote access to your PCRT database for this to work!)',
				'type' => 'text',
				'default' => ''
		),
		'DB_Name' => array(
				'description' => 'PCRT Database Name',
				'type' => 'text',
				'default' => ''
		),
		'DB_User' => array(
				'description' => '',
				'type' => 'text',
				'default' => ''
		),
		'DB_Password' => array(
				'description' => 'PCRT Database Password',
				'type' => 'password',
				'default' => ''
		),
		'Filter_Length' => array(
				'description' => 'The number of rightmost digits to check for a match. Enter zero to disable ',
				'type' => 'number',
				'default' => 10,
		),
	);


	function get_caller_id($thenumber, $run_param=array()) {
		$caller_id = null;

		if(class_exists('PDO')) {
			$this->DebugPrint("Connecting to PCRT Database....");
			try {
				$dbh = new PDO('mysql:dbname='.$run_param['DB_Name'].';host='.$run_param['DB_Host'], $run_param['DB_User'], $run_param['DB_Password']);
			} catch (PDOException $e) {
				$this->DebugPrint('Connection failed: ' . $e->getMessage());
				return null;
			}
		} else {
			$this->DebugPrint("PDO not present on system...Skipping");
			return null;
		}

		// trim number to filter length if applicable
		if ($run_param['Filter_Length'] != 0) {
			if (strlen($thenumber) > $run_param['Filter_Length']) $thenumber = substr($thenumber, -$run_param['Filter_Length']);
		}

		$sql_params = array();
		$sql = 'SELECT * FROM `pc_owner` where `pccellphone` REGEXP :theregex or `pcworkphone` REGEXP :theregex or `pcphone` REGEXP :theregex';

		//  Build regular expression from the $thenumber to avoid non-digit characters stored in database
		$theregex = "[^0-9]*";
		for( $x=0; $x < ((strlen($thenumber))-1); $x++ )  {
			$theregex .=  substr($thenumber,$x,1)."[^0-9]*";
		}
		$theregex = $theregex.(substr($thenumber,-1))."([^0-9]+|$)";
		$sql_params[':theregex'] = $theregex;

		$sth = $dbh->prepare($sql, array(PDO::ATTR_CURSOR => PDO::CURSOR_FWDONLY));
		if(!$sth) {
			$this->DebugPrint("Failed to Prepare the SQL Statement. Are we connected?...Skipping");
			return null;
		}
		$this->DebugPrint("Connected!");
		$this->DebugPrint("Searching Database...");
		$sth->execute($sql_params);
		$find = $sth->fetch(PDO::FETCH_BOTH);
    
		
		if($find && is_array($find)) {
			$this->DebugPrint("Found..");
			//return $find[1];
			$custName = $find['pcname'];
			$custPCID = $find['pcid'];
			$custName = explode(" ",$custName);
            $firstName = $custName[0];
            $lastName = $custName[1];
			
			$sql1 = 'SELECT * FROM `pc_wo` where `pcid` = '.$custPCID;
			$sth1 = $dbh->prepare($sql1, array(PDO::ATTR_CURSOR => PDO::CURSOR_FWDONLY));
		if(!$sth1) {
			$this->DebugPrint("Failed to Prepare the SQL Statement. Are we connected?...Skipping");
			return null;
		}
		$this->DebugPrint("Connected!");
		$this->DebugPrint("Searching Database...");
		$sth1->execute($sql_params);
		$find1 = $sth1->fetch(PDO::FETCH_BOTH);
			$custWOID = $find1['woid'];
			$custStatusId = $find1['pcstatus'];
			
			$sql2 = 'SELECT boxtitle FROM `boxstyles` where `statusid` = '.$custStatusId;
			$sth2 = $dbh->prepare($sql2, array(PDO::ATTR_CURSOR => PDO::CURSOR_FWDONLY));
		if(!$sth2) {
			$this->DebugPrint("Failed to Prepare the SQL Statement. Are we connected?...Skipping");
			return null;
		}
		$this->DebugPrint("Connected!");
		$this->DebugPrint("Searching Database...");
		$sth2->execute($sql_params);
		$find2 = $sth2->fetch(PDO::FETCH_BOTH);
			$custStatus = $find2['boxtitle'];
		
		
			
			return $firstName.' '.$custWOID.' '.$custStatus;
		} else {
			$this->DebugPrint("Not Found");
			return null;
		}
    }
}
