<?php

class PhoneSpamFilter extends superfecta_base {

	public $description, $source_param;
	public $version_requirement = "2.11";

	public function __construct() {
		$this->description = "http://www.phonespamfilter.com - "._("A datasource devoted to identifying telemarketers. These listings are provided by other users of this service.");
		$this->source_param = array(
			'SPAM_Threshold' => array(
				'description' => _('Specify the number of listings required to mark a call as spam.'),
				'type' => 'number',
				'default' => 10
			)
		);
	}

	function get_caller_id($thenumber, $run_param=array()) {

		$caller_id = null;

		if (!$this->IsValidNumber("US,CA", $thenumber)) {
			$this->DebugPrint(_("Skipping Source - Non US/CAN number").": {$thenumber}");
		} else {
			$this->DebugPrint(_("Searching PhoneSpamFilter..."));

			$url = "http://www.phonespamfilter.com/check.php?phone=$thenumber";
			$value = $this->get_url_contents($url);

			if (is_numeric($value)) {
				$this->DebugPrint(_('Found')." ".$value);

				$score = $value;
				if ($score > $run_param['SPAM_Threshold']) {
					$this->spam = true;
					$this->DebugPrint(" "._("determined to be SPAM"));
				} else {
					$this->DebugPrint(_("Not a SPAM caller"));
				}
			} else {
				$this->DebugPrint(_("not found"));
			}
		}

		return($caller_id);
	}

}
