<?php
class Google_Maps_UK extends superfecta_base {

	function settings() {
		//configuration / display parameters
		//The description cannot contain "a" tags, but can contain limited HTML. Some HTML (like the a tags) will break the UI.
		$source_desc = "http://maps.google.co.uk - 	These listings include business data for the UK.<br><br>This data source requires Superfecta Module version 3.0 or higher.";
		$settings['desc'] = $source_desc;
		$settings['version_requirement'] = "3.0";
		return($settings);
	}
	
	function get_caller_id($thenumber,$run_param=array()) {

		$caller_id = null;		

		if(!$this->IsValidNumber('UK', $this->thenumber))
		{
			$this->DebugPrint("Skipping Source - Non UK number: {$this->thenumber}");
		}
		else
		{
			$this->DebugPrint("Searching maps.google.co.uk for number: {$this->thenumber}");
			
			// We'll be searching google maps
			$url = "http://maps.google.co.uk/?mode=search&q={$this->thenumber}";

			// Grab the first result from google maps that matches our phone number
			$pattern="/title:\'{$this->thenumber}.*sxti:\'(.*)\'/U";
			
			if($this->SearchURL($url, $pattern, $match)){
				$caller_id = $this->ExtractMatch($match);
			}
		}

		while($pos=strstr($caller_id, '\x')) {
			// Convert escaped hex to ASCII character  e.g. \x27 to chr(39)
			$caller_id = str_replace(substr($pos,0,4), chr(hexdec(substr($pos,2,2))), $caller_id);
		}
		return $caller_id;		
	}
}