<?php

/***** ***** ***** ***** ***** ***** ***** ***** ***** ***** ***** ***** ***** ***** ***** ***** 
Module Dev Notes:
This module only supports MySQL searches at the moment, but OpenEMR has a fledgeling API
that may (or may not) support CNAM lookups. Possible future feature.
This module relies on the old mysql_ functions and should be upgraded to use the PDO class

History:
2013-12-27 initial commit
2013-12-28 minor query edits by lgaetz
2013-12-30 added checkbox to enable/disable lookups, added search priority, added sort by date desc, add number format option by lgaetz

 ***** ***** ***** ***** ***** ***** ***** ***** ***** ***** ***** ***** ***** ***** ***** *****/

class OpenEMR extends superfecta_base {

	public $description = "Searches a MySQL OpenEMR Database - see http://www.open-emr.org/";
	public $version_requirement = "2.11";
	public $source_param = array(
		'DB_Host' => array(
				'description' => 'Host address of the OpenEMR database. (localhost if the database is on the same server as FreePBX)',
				'type' => 'text',
				'default' => 'localhost',
		),
		'DB_Name' => array(
				'description' => 'Database name of the OpenEMR database',
				'type' => 'text',
				'default' => 'openemr',
		),
		'DB_User' => array(
				'description' => 'Username used to connect to the OpenEMR database',
				'type' => 'text',
				'default' => 'root',
		),
		'DB_Password' => array(
				'description' => 'Password used to connect to the OpenEMR database',
				'type' => 'password',
				'default' => 'passw0rd',
		),
		'Filter_Length' => array(
				'description' => 'The number of rightmost digits to check for a match. Enter zero to disable',
				'type' => 'number',
				'default' => 10,
		),
		'Search_Cell_Number' => array(
				'description' => '1st priority - If enabled, search patient records for cell number and return patient name on match',
				'type' => 'checkbox',
		),
		'Search_Home_Number' => array(
				'description' => '2nd Priority - If enabled and if no match is found with cell number, this option searches home number field and returns patient name on match. This may be undesirable if more than one patient have the same home number.',
				'type' => 'checkbox',
		),		
		'Search_Work_Number' => array(
				'description' => '3rd Priority - If enabled and if no match is found with patient cell or home phone, this option searches the work number field and returns the patient name on match. This may be undesirable if more than one patient have the same employer number.',
				'type' => 'checkbox',
				
		),
		'Result_Format' => array(
				'description' => 'Choose how you want the patient name displayed on the endpoint.',
				'type' => 'select',
				'option' => array(
					1 => 'Last-name, First-name',
					2 => 'First-name Last-name',
				),
		),
		
	);

	function get_caller_id($thenumber, $run_param=array()) {
		$caller_id = null;
		$value = null;

		$this->DebugPrint("Searching OpenEMR ... ");
		
		if ($run_param['Filter_Length'] != 0) {
			if (strlen($thenumber) > $run_param['Filter_Length']) $thenumber = substr($thenumber, -$run_param['Filter_Length']);
		}
		
		$link = mysql_connect($run_param['DB_Host'], $run_param['DB_User'], $run_param['DB_Password'])or die("OpenEMR connection failed:". $run_param['DB_Host']);
		
		if(!mysql_select_db($run_param['DB_Name'])) {
			$this->DebugPrint("OpenEMR database open failed");
			return false;
		}

		//  Build regular expression from the number to avoid non-digit characters stored in database
		$wquery = "'[^0-9]*";
		for( $x=0; $x < ((strlen($thenumber))-1); $x++ ) {
			$wquery .=  substr($thenumber,$x,1)."[^0-9]*" ;
		}
		$wquery = $wquery.(substr($thenumber,-1))."([^0-9]+|$)'";

		// query database first for cell number
		if ($run_param['Search_Cell_Number'] == 'on') {
			$query = "SELECT * FROM `patient_data` where `phone_cell` REGEXP ".$wquery." ORDER BY `date` DESC LIMIT 1";
			$result = mysql_query($query) or die("OpenEMR query failed: $query");
		}

		// search home number if enabled and if no hit on cell
		if ($run_param['Search_Home_Number'] == 'on' && mysql_num_rows($result)== 0) {
			$query = "SELECT * FROM `patient_data` where `phone_home` REGEXP ".$wquery." ORDER BY `date` DESC LIMIT 1";
			$result = mysql_query($query) or die("OpenEMR query failed: $query");
		}

		// search work number if enabled and if no hit on cell or home
		if ($run_param['Search_Work_Number'] == 'on' && mysql_num_rows($result)== 0) {
			$query = "SELECT * FROM `patient_data` where `phone_biz` REGEXP ".$wquery." ORDER BY `date` DESC LIMIT 1";
			$result = mysql_query($query) or die("OpenEMR query failed: $query");
		}

		// Get last & first name if any results are returned from query
		if (mysql_num_rows($result)>0) {
			$row = mysql_fetch_array($result);
			if ($run_param['Result_Format'] == '1') {
				$value = trim($row["lname"].", ".$row["fname"]);
			}
			elseif ($run_param['Result_Format'] == '2') {
				$value = trim($row["fname"]." ".$row["lname"]);
			}
		}

		mysql_close($link);              // close link to database

		if(strlen($value) > 0) {
			$caller_id = trim($value);
		}
		else if($debug) {
			$this->DebugPrint("not found");
		}

		return $caller_id;
	}
}
