<?php

class Yellow_Pages extends superfecta_base {

    public $description = "http://yellowpages.addresses.com - This will return only business listings, it will not return residential listings.";
    public $version_requirement = "2.11";

    function get_caller_id($thenumber, $run_param=array()) {
        $caller_id = null;
        $npa = "";
        $nxx = "";
        $station = "";

        if (!$this->IsValidNumber(array('US', 'CA'), $thenumber, $npa, $nxx, $station)) {
            $this->DebugPrint("Skipping Source - Non Canadian/US number: " . $thenumber);
        } else {
            $this->DebugPrint("Searching Yellow Pages ... ");
            $url = "http://yellowpages.addresses.com/yellow-pages/phone:" . $thenumber . "/listings.html";

            $pattern = '/<td style=\"width: 60%; padding-left: 10px; vertical-align: top; text-align: left;\">(.*)<\/a><\/h2><div class=\"sml_txt\">/i';

            if ($this->SearchURL($url, $pattern, $match, NULL, TRUE)) {
                $caller_id = $this->ExtractMatch($match);
            }
        }
        return($caller_id);
    }

}