<?php
class Google_Maps_UK extends superfecta_base {

	function settings() {
		//configuration / display parameters
		//The description cannot contain "a" tags, but can contain limited HTML. Some HTML (like the a tags) will break the UI.
		$source_desc = "http://maps.google.co.uk - 	These listings include business data for the UK.<br><br>This data source requires Superfecta Module version 3.0 or higher.";
		$settings['desc'] = $source_desc;
		$settings['version_requirement'] = "3.0";
		return($settings);
	}
	
	function get_caller_id($thenumber,$run_param=array()) {

		$caller_id = "";		

		if(!$this->IsValidNumber('UK', $thenumber))
		{
			$this->DebugPrint("Skipping Source - Non UK number: {$thenumber}");
		}
		else
		{
			$this->DebugPrint("Searching maps.google.co.uk for number: {$thenumber}");
			
			// By default, the found name is empty
			$name = "";
	
			// We'll be searching google maps
			$url = "http://maps.google.co.uk/?mode=search&q={$thenumber}";

			// Grab the first result from google maps that matches our phone number
			$pattern="/<span class=\"pp-place-title\">.*><span>(.*)<\/span><\/a>/U";
			
			$this->SearchURL($url, $pattern, $match);
			
			if(isset($match[1]) && strlen($match[1])){
				$name = trim(strip_tags($match[1]));
			}
			// If we found a match, return it
			if(strlen($name) > 1)
			{
				$caller_id = $name;
			}
			else
			{
				$this->DebugPrint("not found");
			}
		}
		return($caller_id);
	}
}