<?php

/*** *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** 
Developer Notes:
This source still relies on mysql_ functions, it should be updated to use the PDO class.
There may be some users who would want this module to do post processing to
	insert name/number into FOP2 address book
Versions prior to 2013-12-20 would abandon the search if there were fewer digits than specified
	in the filter length which I (lgaetz) didn't agree with. 

Versopm History:
20xx-xx-xx	Initial migration to 2.11 platform
2013-12-19	bug fix, CNAM_Type missing from Source Param user input - lgaetz
2013-12-20	bug fix, don't modify $run_param variables inside get_caller_id function, fix filter length - lgaetz

*** *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***/

class FOP2_Phonebook extends superfecta_base {

    public $description = "Look up First Name, Last Name, Company Name in the FOP2 visual address book MySQL table";
    public $version_requirement = "2.11";
    public $source_param = array(
        'DB_Host' => array(
                'description' => 'Host address of the Asteridex database. (localhost if the database is on the same server as FreePBX)',
                'type' => 'text',
				'default' => 'localhost'
        ),
        'DB_Name' => array(
                'description' => 'Database name of the Asteridex database',
                'type' => 'text',
				'default' => 'fop2'
        ),
        'DB_User' => array(
                'description' => 'Username used to connect to the Asteridex database',
                'type' => 'text',
				'default' => 'root'
        ),
        'DB_Password' => array(
                'description' => 'Password used to connect to the Asteridex database',
                'type' => 'password',
				'default' => 'passw0rd'
        ),
		'CNAM_Type' => array(
			'description' => 'Select how returned CNAM is prioritized',
			'type' => 'select',
			'option' => array(
				'1' => 'Company_name then First_name Last_name',
				'2' => 'First_name Last_name then Company_name',
				'3' => 'Last_name Company_name if both exist',
			),
		),
        'Filter_Length' => array(
                'description' => 'The number of rightmost digits to check for a match. Enter zero to disable this setting',
                'type' => 'number',
				'default' => 10
        )
    );

    function get_caller_id($thenumber, $run_param=array()) {
        $caller_id = null;
        $this->DebugPrint("Searching FOP2 ... ");

		// Initialize variables
		$wquery = "";
		$wquery_string = "";
		$wquery_result = "";
		$cnam_type = $run_param['CNAM_Type'];

		//  trim incoming number to specified filter length
		if ($run_param['Filter_Length'] != 0 && strlen($thenumber) > $run_param['Filter_Length']) {
			$thenumber = substr($thenumber, (-1*$run_param['Filter_Length']));
		}
		//  Build regular expression from modified $thenumber to avoid non-digit characters
		$wquery = "'[^0-9]*";
		for( $x=0; $x < ((strlen($thenumber))-1); $x++ ) {
			$wquery .=  substr($thenumber,$x,1)."[^0-9]*" ;
		}
		$wquery = $wquery.(substr($thenumber,-1))."([^0-9]+|$)'";

		//  Connect to database
		$wdb_handle = mysql_connect($run_param['DB_Host'], $run_param['DB_User'], $run_param['DB_Password']) or die("FOP2 connection failed" . mysql_error());
		mysql_select_db($run_param['DB_Name']) or die("FOP2 db open error: " . mysql_error());
		mysql_query("SET NAMES 'utf8'") or die("UTF8 set query  failed: " . mysql_error());

		// search database
		$wquery_string = 'SELECT firstname, lastname, company FROM visual_phonebook WHERE (phone1 REGEXP '.$wquery.') OR (phone2 REGEXP '.$wquery.') ORDER BY id DESC';
		$wquery_result = mysql_query($wquery_string) or die("FOP2 query failed" . mysql_error());
		if (mysql_num_rows($wquery_result)>0) {
			$wquery_row = mysql_fetch_array($wquery_result);
			if ($cnam_type == 3) {
				if ($wquery_row["lastname"] != "" and $wquery_row["company"] != "") {
					$caller_id = $wquery_row["lastname"]." ".$wquery_row["company"];
				} else {
					$cnam_type = 1;
				}
			}
			if ($cnam_type == 1) {
				if ($wquery_row["company"] != "") {
					$caller_id = $wquery_row["company"];
				} else if ($wquery_row["firstname"] != "" and $wquery_row["lastname"] != "") {
					$caller_id = $wquery_row["firstname"]." ".$wquery_row["lastname"];
				} else if ($wquery_row["firstname"] != "") {
					$caller_id = $wquery_row["firstname"];
				} else {
					$caller_id = $wquery_row["lastname"];
				}
			}
			if ($cnam_type == 2) {
				if ($wquery_row["firstname"] != "" and $wquery_row["lastname"] != "") {
					$caller_id = $wquery_row["firstname"]." ".$wquery_row["lastname"];
				} else if ($wquery_row["firstname"] != "") {
					$caller_id = $wquery_row["firstname"];
				} else if ($wquery_row["lastname"] != "") {
					$caller_id = $wquery_row["lastname"];
				} else {
					$caller_id = $wquery_row["company"];
				}
			}
		}

		// Close dbase connection
		mysql_close($wdb_handle);

		if ($caller_id == "") {
			$this->DebugPrint("Not Found");
		}	
		return(trim($caller_id));
    }
}

