<?php
class UKPhoneInfo_UK extends superfecta_base {

	function settings() {
		//configuration / display parameters
		//The description cannot contain "a" tags, but can contain limited HTML. Some HTML (like the a tags) will break the UI.
		$source_desc = "http://www.ukphoneinfo.com - The UK Telephone Code Locator will return the exchange or service area location. No names are returned by this source.<br>Because the data provided is less specific than other sources, this data source is usualy configured near the bottom of the list of active data sources.";
		$settings['desc'] = $source_desc;
		$settings['version_requirement'] = "3.0";
		return($settings);
	}
	
	function get_caller_id($thenumber,$run_param=array()) {
		$caller_id = ""; $name="";		

		// Validate number
		if(!$this->IsValidNumber('UK', $thenumber))
		{
			$this->DebugPrint( "Skipping Source - Non UK number: {$thenumber}" );
		}
		else
		{
			$this->DebugPrint( 'Searching UKPhoneInfo ...');

			$url = "http://www.ukphoneinfo.com/search.php?Submit=Submit&d=nl&GNG={$thenumber}";			

			if($this->SearchURL($url, "=<h2[^>]*>(.*)</h2>=siU", $match)) {
				$caller_id = $this->ExtractMatch($match);
			}
		}
		return($caller_id);
	}
}