<?php

class AsteriDex extends superfecta_base {

    public $description = "Searches an AsteriDex Database - local or remote.";
    public $version_requirement = "2.11";
    public $source_param = array(
        'DB_Host' => array(
                'description' => 'Host address of the Asteridex database. (localhost if the database is on the same server as FreePBX)',
                'type' => 'text',
				'default' => 'localhost'
        ),
        'DB_Name' => array(
                'description' => 'Database name of the Asteridex database',
                'type' => 'text',
				'default' => 'asteridex'
        ),
        'DB_User' => array(
                'description' => 'Username used to connect to the Asteridex database',
                'type' => 'text',
				'default' => 'root'
        ),
        'DB_Password' => array(
                'description' => 'Password used to connect to the Asteridex database',
                'type' => 'password',
				'default' => 'passw0rd'
        ),
        'Filter_Length' => array(
                'description' => 'The number of rightmost digits to check for a match. Enter the word false to disable this setting',
                'type' => 'number',
				'default' => 10
        )
    );

    function get_caller_id($thenumber, $run_param=array()) {
        $caller_id = null;

        $this->DebugPrint("Searching AsteriDex ... ");
		
		if ($run_param['Filter_Length'] != false) {
			if (strlen($wquery_input) > $run_param['Filter_Length']) $wquery_input = substr($wquery_input, -$run_param['Filter_Length']);
		}
		
		$link = mysql_connect($run_param['DB_Host'], $run_param['DB_User'], $run_param['DB_Password'])or die("AsteriDex connection failed:". $run_param['DB_Host']);
		
		if(!mysql_select_db($run_param['DB_Name'])) {
			$this->DebugPrint("AsteriDex data base open failed");
			return false;
		}

		//  Build regular expression from the number to avoid non-digit characters stored in database
		$wquery = "'[^0-9]*";
		for( $x=0; $x < ((strlen($wquery_input))-1); $x++ )
	   	{
			$wquery .=  substr($wquery_input,$x,1)."[^0-9]*" ;
		}
		$wquery = $wquery.(substr($wquery_input,-1))."([^0-9]+|$)'";

		// query database
		$query = "SELECT * FROM `user1` where `out` REGEXP ".$wquery;
		$result = mysql_query($query) or die("AsteriDex query failed: $query");

		// Get first name if any results are returned from query
		if (mysql_num_rows($result)>0)
		{
			$row = mysql_fetch_array($result);
			$value = $row["name"];
		}

		mysql_close($link);              // close link to database

		if(strlen($value) > 0)
		{
			$caller_id = trim($value);
		}
		else if($debug)
		{
			$this->DebugPrint("not found");
		}

        return $caller_id;
    }

}