<?php

class Any_Who extends superfecta_base {

    public $description = "http://whitepages.anywho.com - These listings include data from the AnyWho White Pages data source.";
    public $version_requirement = "3.0";

    function get_caller_id($thenumber, $run_param=array()) {
        $caller_id = null;
        $npa = "";
        $nxx = "";
        $station = "";

        if (!$this->IsValidNumber(array('US', 'CA'), $thenumber, $npa, $nxx, $station)) {
            $this->DebugPrint("Skipping Source - Not a valid US/CAN number: " . $thenumber);
        } else {
            $this->DebugPrint("Searching Any Who with (${npa})${nxx}-${station} ... ");

            $url = "http://whitepages.anywho.com/results.php?&qnpa=$npa&qp=" . $nxx . $station;
            $value = $this->get_url_contents($url);

            $notfound = strpos($value, "class=\"NoResultBar\"");
            $start = strpos($value, "class=\"singleName\"");
            if (!$start) {
                $start = strpos($value, "class=\"resultName\"");
            }
            $value = substr($value, $start + 17);
            $start = strpos($value, "\">");
            $value = substr($value, $start + 2);
            $end = strpos($value, "</div>");
            $value = substr($value, 0, $end);
            $value = strip_tags($value);
            if ($notfound) {
                $value = "";
            }

            // If we found a match, return it
            if (strlen($value) > 1) {
                $caller_id = $value;
            } else {
                $this->DebugPrint("not found");
            }
        }
        return($caller_id);
    }

}