<?php
/*** *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** 
 * Say_No_To_0870_UK superfecta module
 * 
 * Written By: Unknown
 * 
 * Gets caller ID name from the site www.saynoto0870.com
 *
 * Terms of service: https://www.saynoto0870.com/disclaimer.php
 *        As of 2021-07-31 superfecta usage appears to be allowable for personal use
 *                "You may view, download for caching purposes only, and print pages from the website for your own personal use ..."
 * 
 * Version History:
 * 		Unknown    - Initial Release
 * 		2021-07-31 - Review site TOS and update URL FREEPBX-22390
 * 
 *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***/
class Say_No_To_0870_UK extends superfecta_base {	
	public $version_requirement = "2.11";

	public function __construct() {
		$this->description = "http://www.saynoto0870.com - "._("These listings include Non-Geographical Alternative Business Telephone Numbers for the UK.");
	}

	function get_caller_id($thenumber, $run_param=array()) {

		$caller_id = null;

		if (!$this->IsValidNumber('UK', $thenumber)) {
			$this->DebugPrint("Skipping Source - Non UK number: {$thenumber}");
		} else {
			$this->DebugPrint("Searching SayNoTo0870 for number: {$thenumber}");

			// By default, the found name is empty
			$name = "";

			// numbersearch.php requires data to be posted
			$url = "https://www.saynoto0870.com/numbersearch.php";
			$PostData = array("number" => $thenumber);

			// Grab the first result that matches our phone number
			$pattern = '/<tr>\s*<td.*<a.*target=\"_blank\">(.*)<\/a><\/td>/U';

			if ($this->SearchURL($url, $pattern, $match, $PostData)) {
				$caller_id = $this->ExtractMatch($match);
			}
		}
		return($caller_id);
	}

}
