<?php
class Can_White_Pages extends superfecta_base {
	function settings() {
		
		$settings['desc'] = "http://www.whitepages.ca - This site will return residential Canadian listings as well as (at least some) American listings.";
		$settings['version_requirement'] = "3.0";

		return($settings);
	}
	
	function get_caller_id($thenumber,$run_param=array()) {
		$caller_id=null;
		$npa=""; $nxx=""; $station="";
		
		if(!$this->IsValidNumber( array('US','CA') ,$thenumber, $npa, $nxx, $station))
		{
			$this->DebugPrint( "Skipping Source - Non Canadian/American number: ".$thenumber);
		}
		else
		{				
			$this->DebugPrint( "Searching www.whitepages.ca - ({$npa}) {$nxx}-{$station}...");

	 		// By default, there is no match
			$name = "";
	
			$url="http://www.whitepages.ca/phone/1-".$npa."-".$nxx."-".$station;    //working June 19, 2012
	
			$pattern = '/<span class=\"name\"><a href=\".*\">(.*?)<\/a><\/span>/i';  // Residential match working Jun 19, 2012

                        
			// Patterns to search for
			$regexp = array(
				$pattern, 								
				
			);
	
			if($this->SearchURL($url, $regexp, $match,NULL,TRUE)) {
				$caller_id = $this->ExtractMatch($match);
			}
		}
		return($caller_id);
	}
	
}