<?php
class FreeCNAM extends superfecta_base {
	function settings() {

		$settings['desc'] = "http://www.freecnam.org       This data source returns CNAM data listed at FreeCNAM.";
		$settings['version_requirement'] = "3.0";

		return($settings);
	}
	
	function get_caller_id($thenumber,$run_param=array()) {
		
		$caller_id="";
		
		if( (!$this->IsValidNumber('US',$thenumber)) && (!$this->IsValidNumber('CA',$thenumber)) )
		{
			$this->DebugPrint( "Skipping Source - Not a valid US/CAN number: ".$thenumber);
		}
		else
		{
			$this->DebugPrint( "Searching FreeCNAM ... ");
			
			$thenumber = (substr($thenumber,0,1) == 1) ? substr($thenumber,1) : $thenumber;
	        $url = "http://freecnam.org/dip?q=" . $thenumber;
	        $sname =  $this->get_url_contents($url);
	
	        if (strlen($sname) > 1)
	        {
				$caller_id = strip_tags($sname);
	        }
	        else
	        {
	        	$this->DebugPrint("not found");
	        }
		}
		return($caller_id);
	}
	
}