<?php

class Truelocal_AU extends superfecta_base {

    public $description = "http://truelocal.com.au - These listings include business data for AU.";
    public $version_requirement = "3.0";

    function settings() {
        //configuration / display parameters
        //The description cannot contain "a" tags, but can contain limited HTML. Some HTML (like the a tags) will break the UI.
        $source_desc = "http://truelocal.com.au - 	These listings include business data for AU.";

        $settings['desc'] = $source_desc;
        $settings['version_requirement'] = "3.0";

        return($settings);
    }

    function get_caller_id($thenumber, $run_param=array()) {

        $caller_id = null;
        $num1 = "";
        $num2 = "";
        $num3 = "";

        if (!$this->IsValidNumber('AU', $this->thenumber, $num1, $num2, $num3)) {
            $this->DebugPrint("Skipping Source - Non Australian number: {$this->thenumber}");
        } else {
            $this->DebugPrint("Searching truelocal.com.au - {$this->thenumber} ... ");

            // Since truelocal.com.au's has no reverse lookup, we'll use google 
            // to get the proper truelocal.com.au page
            $url = "http://www.google.com/search?num=10&hl=en&lr=&safe=off&as_qdr=all&q=%22" . $num1 . "+" . $num2 . "+" . $num3 . "%22+site%3Awww.truelocal.com.au%2Fbusiness&btnG=Search";

            // Check if we can just pull the name directly from google's index
            $pattern = "/<a href=\"http:\/\/www\.truelocal\.com\.au\/business\/[^>]{1,100}>([^,-<]{1,100})/i";

            if ($this->SearchURL($url, $pattern, $match)) {
                $caller_id = $this->ExtractMatch($match);
            }
        }

        return($caller_id);
    }

}